### ISSUE TITLE
Implement tasrange

### ISSUE THREAD

**Issue by SimonTreu** [ISI-MIP/isi-cfact#60]

**Comment by matthiasmengel** [comment]
This is the current performance by 503a41ef2b2ad93221ba9a9d530a8f6264532bd0 via isicf022_gswp3_tasrange_sub20. This can be improved yet.

![image](https://user-images.githubusercontent.com/1313086/72713193-e607d080-3b6c-11ea-8404-84823bd92cde.png)

**Comment by matthiasmengel** [comment]
Improved via narrower priors via ac4e877984592cf6, see `isicf022_gswp3_tasrange_sub20_sharperslopepriors`
![image](https://user-images.githubusercontent.com/1313086/72733236-ba4e1000-3b97-11ea-918a-96cb79d2f1f0.png)

**Comment by SimonTreu** [comment]
The worst cell in the run on all cells: Looks like an issue with the logistic function ( intercept can not be set as needed)
![Screenshot from 2020-01-30 09-46-08](https://user-images.githubusercontent.com/9370249/73433827-ced39a80-4345-11ea-9f9e-f66df5587056.png)

**Comment by SimonTreu** [comment]
Relu model fixes this cell

![Screenshot from 2020-01-30 19-49-06](https://user-images.githubusercontent.com/9370249/73480136-a4abc800-4399-11ea-89d7-8182b3974b6d.png)

**Comment by SimonTreu** [comment]
with relu. Works at least as good as the logistic model.
![Screenshot from 2020-01-31 09-38-54](https://user-images.githubusercontent.com/9370249/73524856-45d46600-440e-11ea-8b32-297475fa5319.png)

**Comment by matthiasmengel** [comment]
On the full dataset, using RELU via `isicf023_gswp3_tasrange_sub01_relu`. We need to check why some grid cells fail. @SimonTreu any ideas how to deal with the regions that still show significant trend?

![image](https://user-images.githubusercontent.com/1313086/73647375-9ef50180-467b-11ea-9fcb-8f9296eb92ae.png)

**Comment by SimonTreu** [comment]
Fixed when no trend in sigma is modeled
