### ISSUE TITLE
Implement surface downwelling shortwave radiation (rsds)

### ISSUE THREAD

**Issue by matthiasmengel** [ISI-MIP/isi-cfact#64]
Use Beta or Normal distribution. Lange et al. 2019 uses Beta distribution.

**Comment by SimonTreu** [comment]
First implementation with beta distribution seams not to run
see `isicf022_gswp3_rsds`
![isicf022_gswp3_rsds](https://user-images.githubusercontent.com/9370249/72750632-ac12ea80-3bbd-11ea-8811-a27379f05fe8.png)

**Comment by SimonTreu** [comment]
It seems that the model is not able to approximate an appropriate cycle in the variance:
![yearly cycle](https://user-images.githubusercontent.com/9370249/72750673-c6e55f00-3bbd-11ea-8c96-ae6319d8559e.png)

**Comment by SimonTreu** [comment]
![rice](https://user-images.githubusercontent.com/9370249/72759809-13896400-3bd7-11ea-98b4-b57d960b6afb.png)

**Comment by SimonTreu** [comment]
rice distribution works much better.

**Comment by SimonTreu** [comment]
the estimator seems to fail for some cells. The reason is probably bad initial energy because of too small values. A fix would be to include some kind of a threshold an exclude smaller values or give them the threshold value

**Comment by SimonTreu** [comment]
with rice distribution
![rsds_rice_map](https://user-images.githubusercontent.com/9370249/72785314-40fffd00-3c2b-11ea-88dc-6275b2ce1448.png)

**Comment by SimonTreu** [comment]
New model with a normal distribution where the data is censored after quantile mapping returns good detrending results
`isicf022_gswp3_rsds_sub20_normal`
![Screenshot from 2020-01-23 08-56-21](https://user-images.githubusercontent.com/9370249/72966658-ba305900-3dbf-11ea-8da3-88ccdb7f1c36.png)

**Comment by matthiasmengel** [comment]
Excellent! Could that help for `hurs` as well?

**Comment by SimonTreu** [comment]
without yearly cycle in sigma. acceptance probability should be increased to make smaller step size

**Comment by SimonTreu** [comment]
![Screenshot from 2020-01-23 19-49-34](https://user-images.githubusercontent.com/9370249/73014030-bb8e6f80-3e19-11ea-9adf-568bce70c924.png)

**Comment by SimonTreu** [comment]
can fix all erratic cells but one. That cell runs fine locally but not on cluster. Not sure why
![Screenshot from 2020-01-24 17-51-35](https://user-images.githubusercontent.com/9370249/73087186-6d897280-3ed2-11ea-87c6-9bd6918dd086.png)

**Comment by matthiasmengel** [comment]
Results from normal model on sub5 grid

![image](https://user-images.githubusercontent.com/1313086/73459439-29d1b580-4377-11ea-8109-5b7fb361b69a.png)

**Comment by matthiasmengel** [comment]
using normal model, sub01.

![image](https://user-images.githubusercontent.com/1313086/73459799-c3996280-4377-11ea-9fea-c35e592838d3.png)
