### ISSUE TITLE
Implement relative humidity (hurs)

### ISSUE THREAD

**Issue by matthiasmengel** [ISI-MIP/isi-cfact#67]
Use Beta distribution.

**Comment by matthiasmengel** [comment]
@SimonTreu  just realized that this should not use Normal, but Beta. Feel free to overhaul

**Comment by matthiasmengel** [comment]
See 257b7be91d97ed9c7fd435021d.

**Comment by matthiasmengel** [comment]
Not yet there using Beta via `isicf022_gswp3_hurs_sub20_Betadist`.

![image](https://user-images.githubusercontent.com/1313086/72819255-3c5c3880-3c6d-11ea-9935-b12295025061.png)

**Comment by matthiasmengel** [comment]
We do not yet deal correctly with humidity > 100%. Should be set to original values, but is NaN at the moment. 
![image](https://user-images.githubusercontent.com/1313086/72822815-0621b780-3c73-11ea-8efd-6e14e1b48b24.png)

**Comment by SimonTreu** [comment]
![Screenshot from 2020-01-24 10-54-52](https://user-images.githubusercontent.com/9370249/73060411-0d75da80-3e98-11ea-854a-c844407f7324.png)

**Comment by SimonTreu** [comment]
rlds with ` modes = [2,2,1,1]` seems to find a better  fit. The results here are with `modes=[1,1,1,1]`

**Comment by SimonTreu** [comment]
All cells are working now
![Screenshot from 2020-01-24 14-36-40](https://user-images.githubusercontent.com/9370249/73073209-2346c800-3eb7-11ea-8f14-83bf1e23f681.png)

**Comment by matthiasmengel** [comment]
So the latest plot is with modes [2,2,1,1]? How fast is it? Why did cells fail before?

**Comment by SimonTreu** [comment]
no last plot is also with modes [1, 1, 1, 1]. Should be fine for the first version, did not test [2,2,1,1] for all cells.
Cells before failed because of a too small threshold for sigma. Also some cells fail because of a zero gradient, that can be fixed with a second run.
