### ISSUE TITLE
Implement precipitation (pr)

### ISSUE THREAD

**Issue by matthiasmengel** [ISI-MIP/isi-cfact#74]
Results available for full resolution via `isicf023_gswp3_pr_sub01`. Some cells in South America and South Africa fail and need to be inspected.

![image](https://user-images.githubusercontent.com/1313086/73267395-4637eb80-41d9-11ea-94bd-88e747c48f02.png)

**Comment by SimonTreu** [comment]
Failed due to job allocation on the cluster
